name: Publish changes to the wiki

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'rydixulous/Discord-Resources-n-More' }}
    steps:
      - uses: actions/checkout@v1
      # Additional steps to generate documentation in "Wiki_Files" directory
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "Wiki_Files"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
