name: Notify Translators
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Discord notifications
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v25
        with:
          files: wiki/**
      - name: Discord notification
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          DISCORD_WEBHOOK: ${{ secrets.TRANSLATORS_CLUB_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'https://github.com/Discord-Resources-Wiki/Discord-Resources-Wiki/compare/{{ EVENT_PAYLOAD.push.before }}...{{ EVENT_PAYLOAD.push.after }}'
